
package ticketmanagement;;

import java.awt.Toolkit;
import java.util.Calendar;
import java.text.SimpleDateFormat;


public class Ticket extends javax.swing.JFrame {

   

     
    public Ticket() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblDtoP = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rbtnAC = new javax.swing.JRadioButton();
        rbtnNonac = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbtnGet = new javax.swing.JRadioButton();
        rbtnReturn = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rbtnAdult = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rbtnChild = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        cbox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCMobile = new javax.swing.JTextField();
        txtCName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtCClass = new javax.swing.JTextField();
        txtCAdult = new javax.swing.JTextField();
        txtCChild = new javax.swing.JTextField();
        txtCTType = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtCFrom = new javax.swing.JTextField();
        txtCTo = new javax.swing.JTextField();
        txtCDate = new javax.swing.JTextField();
        txtCTime = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtCTno = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtCPrice = new javax.swing.JTextField();
        txtCRoute = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        txtTax = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnTotal = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(java.awt.SystemColor.activeCaption);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblDtoP.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        lblDtoP.setText("                         Greenline Paribahan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDtoP, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDtoP, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
        );

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Class");

        rbtnAC.setBackground(java.awt.SystemColor.activeCaption);
        rbtnAC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rbtnAC.setText("AC");
        rbtnAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnACActionPerformed(evt);
            }
        });

        rbtnNonac.setBackground(java.awt.SystemColor.activeCaption);
        rbtnNonac.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rbtnNonac.setText("NON-AC");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Ticket");

        rbtnGet.setBackground(java.awt.SystemColor.activeCaption);
        rbtnGet.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rbtnGet.setText("Get");

        rbtnReturn.setBackground(java.awt.SystemColor.activeCaption);
        rbtnReturn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rbtnReturn.setText("Return");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Adult");

        rbtnAdult.setBackground(java.awt.SystemColor.activeCaption);
        rbtnAdult.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rbtnAdult.setText("Yes");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Child");

        rbtnChild.setBackground(java.awt.SystemColor.activeCaption);
        rbtnChild.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rbtnChild.setText("Yes");
        rbtnChild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnChildActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Destination");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Name");

        txtName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        cbox.setBackground(java.awt.SystemColor.activeCaption);
        cbox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pabna", "Kashinathpur", "Shirajganj", "Tangail" }));
        cbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Mobile No");

        txtMobile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtMobile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnAC)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbtnNonac))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnGet)
                                    .addComponent(rbtnReturn)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(rbtnAdult))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnChild)
                            .addComponent(jLabel5))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnAC)
                    .addComponent(rbtnGet)
                    .addComponent(rbtnAdult)
                    .addComponent(rbtnChild))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnNonac)
                    .addComponent(rbtnReturn))
                .addGap(17, 17, 17))
        );

        jPanel3.setBackground(java.awt.SystemColor.activeCaption);
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Name");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Mobile No");

        txtCMobile.setEditable(false);
        txtCMobile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMobileActionPerformed(evt);
            }
        });

        txtCName.setEditable(false);
        txtCName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCNameActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Class");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Ticket Type");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Adult");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Child");

        txtCClass.setEditable(false);
        txtCClass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCClassActionPerformed(evt);
            }
        });

        txtCAdult.setEditable(false);
        txtCAdult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtCChild.setEditable(false);
        txtCChild.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtCTType.setEditable(false);
        txtCTType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCTType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCTTypeActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setText("Coustomer Copy");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("From");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("To");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Date");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Time");

        txtCFrom.setEditable(false);
        txtCFrom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtCTo.setEditable(false);
        txtCTo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtCDate.setEditable(false);
        txtCDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtCTime.setEditable(false);
        txtCTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Ticket No");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Price");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Route");

        txtCTno.setEditable(false);
        txtCTno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtCPrice.setEditable(false);
        txtCPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPriceActionPerformed(evt);
            }
        });

        txtCRoute.setEditable(false);
        txtCRoute.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(114, 114, 114))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCMobile))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCClass, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCTType, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCAdult, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(0, 37, Short.MAX_VALUE))
                            .addComponent(txtCChild)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(txtCTime))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(txtCTo)
                                    .addComponent(txtCDate))))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel27)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtCTno)
                            .addComponent(txtCPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCRoute, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel19)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txtCMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCTType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCAdult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCChild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtCFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtCTno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtCTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel27)
                    .addComponent(txtCPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(txtCDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCRoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtCTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(java.awt.SystemColor.activeCaption);
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Sub Total");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Tax");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Total");

        txtSubTotal.setEditable(false);
        txtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTotalActionPerformed(evt);
            }
        });

        txtTax.setEditable(false);
        txtTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTotal.setText("Total");
        btnTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTotalMouseClicked(evt);
            }
        });
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(txtTax)
                            .addComponent(txtSubTotal))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnReset)
                    .addComponent(btnTotal))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnChildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnChildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnChildActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubTotalActionPerformed

    private void txtCNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCNameActionPerformed

    private void txtCTTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCTTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCTTypeActionPerformed

    private void txtCMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCMobileActionPerformed

    private void txtCPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPriceActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtCName.setText(null);
        txtCMobile.setText(null);
        
        
        txtSubTotal.setText(null);
        txtTax.setText(null);
        txtTotal.setText(null);
        txtCTno.setText(null);
        txtCPrice.setText(null);
        txtCRoute.setText(null);
        txtCTType.setText(null);
        txtCAdult.setText(null);
        txtCChild.setText(null);
        txtCClass.setText(null);
        
        
        txtCTime.setText(null);
        txtCDate.setText(null);
        txtCFrom.setText(null);
        txtCTo.setText(null);
        txtCTno.setText(null);
        txtCRoute.setText(null);
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtCClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCClassActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
         
        String name=txtName.getText();
        String mob=txtMobile.getText();
        
        txtCName.setText(name);
        txtCMobile.setText(mob);

        //=================Time================
        Calendar timer=Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime= new SimpleDateFormat("HH:mm:ss");
        txtCTime.setText(tTime.format(timer.getTime()));
        
        //================Date==================
        SimpleDateFormat Tdate= new SimpleDateFormat("dd/MM/yyyy");
        txtCDate.setText(Tdate.format(timer.getTime()));
        
        txtCFrom.setText("Dhaka");
        txtCTo.setText((String)cbox.getSelectedItem()+" *");
        
        //================Random Number Generator==========
        int num1;
        String q1="";
        num1=1325+(int)(Math.random()*4238);
        q1+=num1+1325;
        txtCTno.setText(q1);
        
        
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTotalMouseClicked
       
        double ShirajganjAC=750;
        double KashinathpurAC=900;
        double TangailAC=650;
        double PabnaAC=1000;
        
        double tax=15;
        double Shirajganj=450;
        double Kashinathpur=500;
        double Tangail=350;
        double Pabna=550;
        double totalcost;
        
        
        //===========================For Pabna AC======================
        
        if((rbtnAC.isSelected())&&(rbtnGet.isSelected())&& (rbtnAdult.isSelected())&&(cbox.getSelectedItem().equals("Pabna")))
                {
                    
                    
                    totalcost=(tax*PabnaAC)/100;
                    String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText(sTax);
                    String subTotal=String.format("%.2f TK",PabnaAC);
                    txtSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",PabnaAC+totalcost);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Get");
                    txtCAdult.setText("ONE");
                    txtCChild.setText("Nil");
                    txtCClass.setText("AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        else if((rbtnAC.isSelected())&&(rbtnGet.isSelected())&& (rbtnChild.isSelected())&&(cbox.getSelectedItem().equals("Pabna")))
                {
                    
                    
                    //totalcost=(tax*Pabna)/100;
                    //String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText("null");
                    String subTotal=String.format("%.2f TK",PabnaAC);
                    txtSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",PabnaAC);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Get");
                    txtCAdult.setText("Nil");
                    txtCChild.setText("ONE");
                    txtCClass.setText("AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        else if((rbtnAC.isSelected())&&(rbtnReturn.isSelected())&& (rbtnAdult.isSelected())&&(cbox.getSelectedItem().equals("Pabna")))
                {
                    
                    
                    totalcost=(tax*PabnaAC)/100;
                    String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText(sTax);
                    //String subTotal=String.format("%.2f TK",Pabna);
                    //jlblSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",totalcost);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Return");
                    txtCAdult.setText("One");
                    txtCChild.setText("Nil");
                    txtCClass.setText("AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        else if((rbtnAC.isSelected())&&(rbtnReturn.isSelected())&& (rbtnChild.isSelected())&&(cbox.getSelectedItem().equals("Pabna")))
                {
                    
                    
                    totalcost=(tax*PabnaAC)/100;
                    String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText(sTax);
                    //String subTotal=String.format("%.2f TK",Pabna);
                    //jlblSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",totalcost);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Return");
                    txtCAdult.setText("NIL");
                    txtCChild.setText("One");
                    txtCClass.setText("AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        
        //==================================Pabna NON AC==========================
        
        else if((rbtnNonac.isSelected())&&(rbtnGet.isSelected())&& (rbtnAdult.isSelected())&&(cbox.getSelectedItem().equals("Pabna")))
                {
                    
                    
                    totalcost=(tax*Pabna)/100;
                    String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText(sTax);
                    String subTotal=String.format("%.2f TK",Pabna);
                    txtSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",Pabna+totalcost);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Get");
                    txtCAdult.setText("One");
                    txtCChild.setText("Nil");
                    txtCClass.setText("NON AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        else if((rbtnNonac.isSelected())&&(rbtnGet.isSelected())&& (rbtnChild.isSelected())&&(cbox.getSelectedItem().equals("Pabna")))
                {
                    
                    
                    //totalcost=(tax*Pabna)/100;
                    //String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText("null");
                    String subTotal=String.format("%.2f TK",Pabna);
                    txtSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",Pabna);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Get");
                    txtCAdult.setText("Nil");
                    txtCChild.setText("Child");
                    txtCClass.setText("NON AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        else if((rbtnNonac.isSelected())&&(rbtnReturn.isSelected())&& (rbtnAdult.isSelected())&&(cbox.getSelectedItem().equals("Pabna")))
                {
                    
                    
                    totalcost=(tax*Pabna)/100;
                    String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText(sTax);
                    //String subTotal=String.format("%.2f TK",Pabna);
                    //jlblSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",totalcost);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Return");
                    txtCAdult.setText("One");
                    txtCChild.setText("Nil");
                    txtCClass.setText("NON AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        else if((rbtnNonac.isSelected())&&(rbtnReturn.isSelected())&& (rbtnChild.isSelected())&&(cbox.getSelectedItem().equals("Pabna")))
                {
                    
                    
                    totalcost=(tax*Pabna)/100;
                    String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText(sTax);
                    //String subTotal=String.format("%.2f TK",Pabna);
                    //jlblSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",totalcost);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Return");
                    txtCAdult.setText("NIL");
                    txtCChild.setText("One");
                    txtCClass.setText("NON AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        
        //=============================AC Kashinathpur==============================
        
        
        else if((rbtnAC.isSelected())&&(rbtnGet.isSelected())&& (rbtnAdult.isSelected())&&(cbox.getSelectedItem().equals("Kashinathpur")))
                {
                    totalcost=(tax*KashinathpurAC)/100;
                    String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText(sTax);
                    String subTotal=String.format("%.2f TK",KashinathpurAC);
                    txtSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",KashinathpurAC+totalcost);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("GET");
                    txtCAdult.setText("One");
                    txtCChild.setText("Nil");
                    txtCClass.setText("AC");
                    txtCRoute.setText("Dhaka-Pabna");
                } 
        
        
        
        else if((rbtnAC.isSelected())&&(rbtnGet.isSelected())&& (rbtnChild.isSelected())&&(cbox.getSelectedItem().equals("Kashinathpur")))
                {
                    
                    
                    //totalcost=(tax*Pabna)/100;
                    //String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText("null");
                    String subTotal=String.format("%.2f TK",KashinathpurAC);
                    txtSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",KashinathpurAC);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Get");
                    txtCAdult.setText("Nil");
                    txtCChild.setText("ONE");
                    txtCClass.setText("AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        else if((rbtnAC.isSelected())&&(rbtnReturn.isSelected())&& (rbtnAdult.isSelected())&&(cbox.getSelectedItem().equals("Kashinathpur")))
                {
                    
                    
                    totalcost=(tax*KashinathpurAC)/100;
                    String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText(sTax);
                    //String subTotal=String.format("%.2f TK",Pabna);
                    //jlblSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",totalcost);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Return");
                    txtCAdult.setText("One");
                    txtCChild.setText("Nil");
                    txtCClass.setText("AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        else if((rbtnAC.isSelected())&&(rbtnReturn.isSelected())&& (rbtnChild.isSelected())&&(cbox.getSelectedItem().equals("Kashinathpurt")))
                {
                    
                    
                    totalcost=(tax*KashinathpurAC)/100;
                    String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText(sTax);
                    //String subTotal=String.format("%.2f TK",Pabna);
                    //jlblSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",totalcost);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Return");
                    txtCAdult.setText("NIL");
                    txtCChild.setText("One");
                    txtCClass.setText("AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        
        //==================================Kashinathpur NON AC==========================
        
        else if((rbtnNonac.isSelected())&&(rbtnGet.isSelected())&& (rbtnAdult.isSelected())&&(cbox.getSelectedItem().equals("Kashinathpur")))
                {
                    
                    
                    totalcost=(tax*Kashinathpur)/100;
                    String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText(sTax);
                    String subTotal=String.format("%.2f TK",Kashinathpur);
                    txtSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",Kashinathpur+totalcost);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Get");
                    txtCAdult.setText("One");
                    txtCChild.setText("Nil");
                    txtCClass.setText("NON AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        else if((rbtnNonac.isSelected())&&(rbtnGet.isSelected())&& (rbtnChild.isSelected())&&(cbox.getSelectedItem().equals("Kashinathpur")))
                {
                    
                    
                    //totalcost=(tax*Pabna)/100;
                    //String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText("null");
                    String subTotal=String.format("%.2f TK",Kashinathpur);
                    txtSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",Kashinathpur);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Get");
                    txtCAdult.setText("Nil");
                    txtCChild.setText("Child");
                    txtCClass.setText("NON AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        else if((rbtnNonac.isSelected())&&(rbtnReturn.isSelected())&& (rbtnAdult.isSelected())&&(cbox.getSelectedItem().equals("Kashinathpur")))
                {
                    
                    
                    totalcost=(tax*Kashinathpur)/100;
                    String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText(sTax);
                    //String subTotal=String.format("%.2f TK",Pabna);
                    //jlblSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",totalcost);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Return");
                    txtCAdult.setText("One");
                    txtCChild.setText("Nil");
                    txtCClass.setText("NON AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        else if((rbtnNonac.isSelected())&&(rbtnReturn.isSelected())&& (rbtnChild.isSelected())&&(cbox.getSelectedItem().equals("Kashinathpur")))
                {
                    
                    
                    totalcost=(tax*Kashinathpur)/100;
                    String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText(sTax);
                    //String subTotal=String.format("%.2f TK",Pabna);
                    //jlblSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",totalcost);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Return");
                    txtCAdult.setText("NIL");
                    txtCChild.setText("One");
                    txtCClass.setText("NON AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        
        
        //===============================AC Shirajganj=================================
        
        else if((rbtnAC.isSelected())&&(rbtnGet.isSelected())&& (rbtnAdult.isSelected())&&(cbox.getSelectedItem().equals("Shirajganj")))
                {
                    totalcost=(tax*ShirajganjAC)/100;
                    String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText(sTax);
                    String subTotal=String.format("%.2f TK",ShirajganjAC);
                    txtSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",ShirajganjAC+totalcost);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("GET");
                    txtCAdult.setText("One");
                    txtCChild.setText("Nil");
                    txtCClass.setText("AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        else if((rbtnAC.isSelected())&&(rbtnGet.isSelected())&& (rbtnChild.isSelected())&&(cbox.getSelectedItem().equals("Shirajganj")))
                {
                    
                    
                    //totalcost=(tax*Pabna)/100;
                    //String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText("null");
                    String subTotal=String.format("%.2f TK",ShirajganjAC);
                    txtSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",ShirajganjAC);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Get");
                    txtCAdult.setText("Nil");
                    txtCChild.setText("ONE");
                    txtCClass.setText("AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        else if((rbtnAC.isSelected())&&(rbtnReturn.isSelected())&& (rbtnAdult.isSelected())&&(cbox.getSelectedItem().equals("Shirajganj")))
                {
                    
                    
                    totalcost=(tax*ShirajganjAC)/100;
                    String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText(sTax);
                    //String subTotal=String.format("%.2f TK",Pabna);
                    //jlblSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",totalcost);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Return");
                    txtCAdult.setText("One");
                    txtCChild.setText("Nil");
                    txtCClass.setText("AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        else if((rbtnAC.isSelected())&&(rbtnReturn.isSelected())&& (rbtnChild.isSelected())&&(cbox.getSelectedItem().equals("Shirajganj")))
                {
                    
                    
                    totalcost=(tax*ShirajganjAC)/100;
                    String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText(sTax);
                    //String subTotal=String.format("%.2f TK",Pabna);
                    //jlblSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",totalcost);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Return");
                    txtCAdult.setText("NIL");
                    txtCChild.setText("One");
                    txtCClass.setText("AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        
        //==================================Shirajganj NON AC==========================
        
        else if((rbtnNonac.isSelected())&&(rbtnGet.isSelected())&& (rbtnAdult.isSelected())&&(cbox.getSelectedItem().equals("Shirajganj")))
                {
                    
                    
                    totalcost=(tax*Shirajganj)/100;
                    String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText(sTax);
                    String subTotal=String.format("%.2f TK",Shirajganj);
                    txtSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",Shirajganj+totalcost);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Get");
                    txtCAdult.setText("One");
                    txtCChild.setText("Nil");
                    txtCClass.setText("NON AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        else if((rbtnNonac.isSelected())&&(rbtnGet.isSelected())&& (rbtnChild.isSelected())&&(cbox.getSelectedItem().equals("Shirajganj")))
                {
                    
                    
                    //totalcost=(tax*Pabna)/100;
                    //String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText("null");
                    String subTotal=String.format("%.2f TK",Shirajganj);
                    txtSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",Shirajganj);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Get");
                    txtCAdult.setText("Nil");
                    txtCChild.setText("Child");
                    txtCClass.setText("NON AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        else if((rbtnNonac.isSelected())&&(rbtnReturn.isSelected())&& (rbtnAdult.isSelected())&&(cbox.getSelectedItem().equals("Shirajganj")))
                {
                    
                    
                    totalcost=(tax*Shirajganj)/100;
                    String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText(sTax);
                    //String subTotal=String.format("%.2f TK",Pabna);
                    //jlblSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",totalcost);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Return");
                    txtCAdult.setText("One");
                    txtCChild.setText("Nil");
                    txtCClass.setText("NON AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        else if((rbtnNonac.isSelected())&&(rbtnReturn.isSelected())&& (rbtnChild.isSelected())&&(cbox.getSelectedItem().equals("Shirajganj")))
                {
                    
                    
                    totalcost=(tax*Shirajganj)/100;
                    String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText(sTax);
                    //String subTotal=String.format("%.2f TK",Pabna);
                    //jlblSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",totalcost);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Return");
                    txtCAdult.setText("NIL");
                    txtCChild.setText("One");
                    txtCClass.setText("NON AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        
        
        
        //========================AC Tangail==========================================
        
        else if((rbtnAC.isSelected())&&(rbtnGet.isSelected())&& (rbtnAdult.isSelected())&&(cbox.getSelectedItem().equals("Tangail")))
                {
                    totalcost=(tax*TangailAC)/100;
                    String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText(sTax);
                    String subTotal=String.format("%.2f TK",TangailAC);
                    txtSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",TangailAC+totalcost);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("GET");
                    txtCAdult.setText("One");
                    txtCChild.setText("Nil");
                   txtCClass.setText("AC");
                   txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        
        else if((rbtnAC.isSelected())&&(rbtnGet.isSelected())&& (rbtnChild.isSelected())&&(cbox.getSelectedItem().equals("Tangail")))
                {
                    
                    
                    //stotalcost=(tax*Pabna)/100;
                    //String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText("null");
                    String subTotal=String.format("%.2f TK",TangailAC);
                    txtSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",TangailAC);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Get");
                    txtCAdult.setText("Nil");
                    txtCChild.setText("ONE");
                    txtCClass.setText("AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        else if((rbtnAC.isSelected())&&(rbtnReturn.isSelected())&& (rbtnAdult.isSelected())&&(cbox.getSelectedItem().equals("Tangail")))
                {
                    
                    
                    totalcost=(tax*TangailAC)/100;
                    String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText(sTax);
                    //String subTotal=String.format("%.2f TK",Pabna);
                    //jlblSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",totalcost);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Return");
                    txtCAdult.setText("One");
                    txtCChild.setText("Nil");
                    txtCClass.setText("AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        else if((rbtnAC.isSelected())&&(rbtnReturn.isSelected())&& (rbtnChild.isSelected())&&(cbox.getSelectedItem().equals("Tangail")))
                {
                    
                    
                    totalcost=(tax*TangailAC)/100;
                    String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText(sTax);
                    //String subTotal=String.format("%.2f TK",Pabna);
                    //jlblSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",totalcost);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Return");
                    txtCAdult.setText("NIL");
                    txtCChild.setText("One");
                    txtCClass.setText("AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        
        //==================================Tangail NON AC==========================
        
        else if((rbtnNonac.isSelected())&&(rbtnGet.isSelected())&& (rbtnAdult.isSelected())&&(cbox.getSelectedItem().equals("Tangail")))
                {
                    
                    
                    totalcost=(tax*Tangail)/100;
                    String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText(sTax);
                    String subTotal=String.format("%.2f TK",Tangail);
                    txtSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",Tangail+totalcost);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Get");
                    txtCAdult.setText("One");
                    txtCChild.setText("Nil");
                    txtCClass.setText("NON AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        else if((rbtnNonac.isSelected())&&(rbtnGet.isSelected())&& (rbtnChild.isSelected())&&(cbox.getSelectedItem().equals("Tangail")))
                {
                    
                    
                    //totalcost=(tax*Pabna)/100;
                    //String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText("null");
                    String subTotal=String.format("%.2f TK",Tangail);
                    txtSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",Tangail);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Get");
                    txtCAdult.setText("Nil");
                    txtCChild.setText("Child");
                    txtCClass.setText("NON AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        else if((rbtnNonac.isSelected())&&(rbtnReturn.isSelected())&& (rbtnAdult.isSelected())&&(cbox.getSelectedItem().equals("Tangail")))
                {
                    
                    
                    totalcost=(tax*Tangail)/100;
                    String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText(sTax);
                    //String subTotal=String.format("%.2f TK",Pabna);
                    //jlblSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",totalcost);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Return");
                    txtCAdult.setText("One");
                    txtCChild.setText("Nil");
                    txtCClass.setText("NON AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        else if((rbtnNonac.isSelected())&&(rbtnReturn.isSelected())&& (rbtnChild.isSelected())&&(cbox.getSelectedItem().equals("Tangail")))
                {
                    
                    
                    totalcost=(tax*Tangail)/100;
                    String sTax=String.format("%.2f TK",totalcost);
                    txtTax.setText(sTax);
                    //String subTotal=String.format("%.2f TK",Pabna);
                    //jlblSubTotal.setText(subTotal);
                    String Total= String.format("%.2f TK",totalcost);
                    txtTotal.setText(Total);
                    txtCPrice.setText(Total);
                    txtCTType.setText("Return");
                    txtCAdult.setText("NIL");
                    txtCChild.setText("One");
                    txtCClass.setText("NON AC");
                    txtCRoute.setText("Dhaka-Pabna");
                    
                } 
        
        
        
    }//GEN-LAST:event_btnTotalMouseClicked

    private void cboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxActionPerformed

    private void rbtnACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnACActionPerformed

    /**
     * @param args the command line arguments
     */
  public static void main(String args[]) {
       /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
      //</editor-fold>
      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {               new Ticket().setVisible(true);
           }
      });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JComboBox<String> cbox;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblDtoP;
    private javax.swing.JRadioButton rbtnAC;
    private javax.swing.JRadioButton rbtnAdult;
    private javax.swing.JRadioButton rbtnChild;
    private javax.swing.JRadioButton rbtnGet;
    private javax.swing.JRadioButton rbtnNonac;
    private javax.swing.JRadioButton rbtnReturn;
    private javax.swing.JTextField txtCAdult;
    private javax.swing.JTextField txtCChild;
    private javax.swing.JTextField txtCClass;
    private javax.swing.JTextField txtCDate;
    private javax.swing.JTextField txtCFrom;
    private javax.swing.JTextField txtCMobile;
    private javax.swing.JTextField txtCName;
    private javax.swing.JTextField txtCPrice;
    private javax.swing.JTextField txtCRoute;
    private javax.swing.JTextField txtCTType;
    private javax.swing.JTextField txtCTime;
    private javax.swing.JTextField txtCTno;
    private javax.swing.JTextField txtCTo;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTax;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Bus.jpg")));
    }
}
